### ISSUE TITLE
Gateway timeout 

### ISSUE THREAD

**Issue by microfuge** [bernt-matthias/ufz-galaxy-scripts#1]
Hi Bernt,

First of all thanks for the scripts.  The are not only useful but via them I learn about bioblend as well. I tried the script `install_container.py` using only  one container. The singularity is fired and the container is downloaded fine. But I also get a gateway timeout with - 
```
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
```
The container download is not affected/killed by this. 

I have already set the timeout in nginx config to 300 seconds. I would be grateful for your advice in this regard especially when multiple tools are specified. 
Thanks

**Comment by bernt-matthias** [comment]
The script already just installs the containers tool by tool for that reason: only a single tool: `[tool]` is passed [here](https://github.com/bernt-matthias/ufz-galaxy-scripts/blob/d0a629755fa92d3cea48a7a39298883781d2feaf/container/install_container.py#L109) and [here](https://github.com/bernt-matthias/ufz-galaxy-scripts/blob/d0a629755fa92d3cea48a7a39298883781d2feaf/container/install_container.py#L123C39-L123C54)

Apart from this I can only redirect you to  https://docs.galaxyproject.org/en/master/admin/nginx.html .. I guess. 

Feel free to reopen if needed.
